# Generated by Django 5.1.2 on 2024-10-14 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default='Uncategorized', null=True, on_delete=django.db.models.deletion.SET_NULL, to='post.category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='media/post_default.jpg', null=True, upload_to='media'),
        ),
    ]
