# Generated by Django 5.1.1 on 2024-10-19 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_comments_delete_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Sin etiquetas', max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
