# Generated by Django 5.1.1 on 2024-10-19 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_tags_post_alter_tags_name'),
    ]

    operations = [
    ]
